// Generated by h200/stage_allocation/generate_contract.py; do not edit.
export const CAMPAIGN = {
  "allowedStates": [
    null,
    "running",
    "finished"
  ],
  "authorizationManifestSha256": "3b35599229a087d6d069478a695e55a1ae1238132978d5a39eec7a330b4888d3",
  "campaignId": "h200-imagenet100-stage-allocation-s501-v3",
  "entity": "daehwa",
  "graphqlEnvelopeKeys": {
    "CreateRunFiles": [
      "operationName",
      "query",
      "variables"
    ],
    "ProbeServerCapabilities": [
      "query",
      "variables"
    ],
    "RunResumeStatus": [
      "operationName",
      "query",
      "variables"
    ],
    "RunStoppedStatus": [
      "operationName",
      "query",
      "variables"
    ],
    "ServerFeaturesQuery": [
      "operationName",
      "query"
    ],
    "UpsertBucket": [
      "operationName",
      "query",
      "variables"
    ],
    "Viewer": [
      "query",
      "variables"
    ]
  },
  "graphqlOperations": {
    "CreateRunFiles": "66f378732e60ffebf606025796ebd6515971be93fae2716730ef9a0fe6532997",
    "ProbeServerCapabilities": "199320da83c03c5613aa66a759d333a32ebba1c44068a79f98be6733f249eae4",
    "RunResumeStatus": "a5605080f3769fa833cde5195012079fce1f2138f52377db5861d4c1b86a6082",
    "RunStoppedStatus": "d951e425fa91e971528ae94226cdc06b9d6dde7f07929d8548e9a4a4f9a323cc",
    "ServerFeaturesQuery": "4ebf7664b24d74a90fa96ce71f8616d9838f25bc5f8b0c41e4223bc0144a2991",
    "UpsertBucket": "a30f4b9373ef4d200d9e927fe21315320dc83fc409c70a7ed64201a2b107bf6d",
    "Viewer": "e5782f8ad76269e0104b45e78e82bc03efcc6783ec68299ac082de12c5475a33"
  },
  "group": "h200-imagenet100-stage-allocation-s501-v3",
  "manifestSha256": "3d0d0d5436aae967db3b34364ea5f6a19f54424c4984c6af1e8cc0e57c6a6a16",
  "maxFileStreamBodyBytes": 10485760,
  "maxGraphqlBodyBytes": 1048576,
  "noVariableOperations": [
    "ProbeServerCapabilities",
    "Viewer",
    "ServerFeaturesQuery"
  ],
  "program": "h200/run_imagenet100_stage_allocation.sh",
  "project": "alphabet2d-imagenet100-h200",
  "protocolVersion": "wandb-0.22.3-h200-imagenet100-stage-v3",
  "runFiles": [
    "config.yaml",
    "wandb-summary.json"
  ],
  "runsById": {
    "08f53ad9f4022795": {
      "displayName": "H200-I100-S501-05-K128-P160-160-160-96-D2222",
      "group": "h200-imagenet100-stage-allocation-s501-v3",
      "program": "h200/run_imagenet100_stage_allocation.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "0bf15f94ec901bde": {
      "displayName": "H200-I100-S501-02-B-K128-P160-160-192-128-D2262",
      "group": "h200-imagenet100-d2262-p-schedule-s501-v2",
      "program": "h200/run_imagenet100_d2262_p_schedule.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "D2262",
        "P-schedule",
        "seed501",
        "authenticated"
      ]
    },
    "176b84265208f096": {
      "displayName": "H200-I100-S501-04-K128-P160-160-160-128-D2222",
      "group": "h200-imagenet100-stage-allocation-s501-v3",
      "program": "h200/run_imagenet100_stage_allocation.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "1f280e808681c775": {
      "displayName": "H200-I100-S501-07-K128-P96-128-160-96-D2222",
      "group": "h200-imagenet100-stage-allocation-s501-v3",
      "program": "h200/run_imagenet100_stage_allocation.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "238915e7e8cd806a": {
      "displayName": "H200-I100-S501-13-K128-P128x4-D2262-FullSR14x4",
      "group": "h200-imagenet100-stage-allocation-s501-v3",
      "program": "h200/run_imagenet100_stage_allocation.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "2468c0113b0107a4": {
      "displayName": "H200-I100-S501-05-E-K128-P128-192-192-128-D2262",
      "group": "h200-imagenet100-d2262-p-schedule-s501-v2",
      "program": "h200/run_imagenet100_d2262_p_schedule.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "D2262",
        "P-schedule",
        "seed501",
        "authenticated"
      ]
    },
    "262eb7ac769a3c51": {
      "displayName": "H200-I100-S501-06-K128-P128-128-160-96-D2222",
      "group": "h200-imagenet100-stage-allocation-s501-v3",
      "program": "h200/run_imagenet100_stage_allocation.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "3a69c73ca80fb205": {
      "displayName": "H200-I100-S501-06-F-K128-P128-160-192-128-D2262",
      "group": "h200-imagenet100-d2262-p-schedule-s501-v2",
      "program": "h200/run_imagenet100_d2262_p_schedule.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "D2262",
        "P-schedule",
        "seed501",
        "authenticated"
      ]
    },
    "555fbdd208c93cd0": {
      "displayName": "H200-I100-S501-12-K128-P128x4-D2242-FullSR14x2",
      "group": "h200-imagenet100-stage-allocation-s501-v3",
      "program": "h200/run_imagenet100_stage_allocation.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "793acdf9c5264018": {
      "displayName": "H200-I100-S501-03-C-K128-P160-192-160-128-D2262",
      "group": "h200-imagenet100-d2262-p-schedule-s501-v2",
      "program": "h200/run_imagenet100_d2262_p_schedule.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "D2262",
        "P-schedule",
        "seed501",
        "authenticated"
      ]
    },
    "8d3c78a5a6b9a525": {
      "displayName": "H200-I100-Reader-WL-relay-canary-v1",
      "group": "h200-imagenet100-reader-wl-s501-v1",
      "program": "h200/run_imagenet100_reader_wl.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "Reader-study",
        "strict-vs-WL",
        "relay-canary"
      ]
    },
    "92b202e12ca21a96": {
      "displayName": "H200-I100-S501-09-K96-P128x4-D2222",
      "group": "h200-imagenet100-stage-allocation-s501-v3",
      "program": "h200/run_imagenet100_stage_allocation.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "94b93f2be45b84e7": {
      "displayName": "H200-I100-S501-01-StrictReader-K96-128-128-128-P128-192-192-128-D2262",
      "group": "h200-imagenet100-reader-wl-s501-v1",
      "program": "h200/run_imagenet100_reader_wl.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "Reader-study",
        "strict-vs-WL",
        "seed501",
        "authenticated"
      ]
    },
    "a5479be2824e7c8f": {
      "displayName": "H200-I100-S501-01-A-K128-P160-160-160-128-D2262",
      "group": "h200-imagenet100-d2262-p-schedule-s501-v2",
      "program": "h200/run_imagenet100_d2262_p_schedule.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "D2262",
        "P-schedule",
        "seed501",
        "authenticated"
      ]
    },
    "a5aeb2225a2fc909": {
      "displayName": "H200-I100-S501-08-K128-P96x4-D2222",
      "group": "h200-imagenet100-stage-allocation-s501-v3",
      "program": "h200/run_imagenet100_stage_allocation.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "acc2724d5b11b2ce": {
      "displayName": "H200-I100-D2262-P-schedule-relay-canary-v2",
      "group": "h200-imagenet100-d2262-p-schedule-s501-v2",
      "program": "h200/run_imagenet100_d2262_p_schedule.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "D2262",
        "P-schedule",
        "relay-canary"
      ]
    },
    "c0a2a6340bac8bf8": {
      "displayName": "H200-I100-stage-relay-permanent-canary-v3",
      "group": "h200-imagenet100-stage-allocation-s501-v3",
      "program": "h200/run_imagenet100_stage_allocation.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "relay-canary",
        "authenticated"
      ]
    },
    "c1f1f99432bcdf88": {
      "displayName": "H200-I100-S501-03-K128-P128-160-160-128-D2222",
      "group": "h200-imagenet100-stage-allocation-s501-v3",
      "program": "h200/run_imagenet100_stage_allocation.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "c6e6a8d87921c54d": {
      "displayName": "H200-I100-S501-11-K128-P128x4-D2223-FullSR7x1",
      "group": "h200-imagenet100-stage-allocation-s501-v3",
      "program": "h200/run_imagenet100_stage_allocation.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "c89e19eea60670ca": {
      "displayName": "H200-I100-S501-04-D-K128-P160-192-192-128-D2262",
      "group": "h200-imagenet100-d2262-p-schedule-s501-v2",
      "program": "h200/run_imagenet100_d2262_p_schedule.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "D2262",
        "P-schedule",
        "seed501",
        "authenticated"
      ]
    },
    "d1f895e5782fc9c0": {
      "displayName": "H200-I100-S501-01-K128-P128x4-D2222-Control",
      "group": "h200-imagenet100-stage-allocation-s501-v3",
      "program": "h200/run_imagenet100_stage_allocation.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "db8432a5f68cd22b": {
      "displayName": "H200-I100-S501-02-K128-P128-128-160-128-D2222",
      "group": "h200-imagenet100-stage-allocation-s501-v3",
      "program": "h200/run_imagenet100_stage_allocation.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "ec1cc3cd87618da8": {
      "displayName": "H200-I100-S501-10-K128-P128x4-D2232-FullSR14x1",
      "group": "h200-imagenet100-stage-allocation-s501-v3",
      "program": "h200/run_imagenet100_stage_allocation.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "f7c55ca5b25880b7": {
      "displayName": "H200-I100-S501-02-WLReader-K96-128-128-128-P128-192-192-128-D2262",
      "group": "h200-imagenet100-reader-wl-s501-v1",
      "program": "h200/run_imagenet100_reader_wl.sh",
      "tags": [
        "H200",
        "ImageNet-100",
        "Reader-study",
        "strict-vs-WL",
        "seed501",
        "authenticated"
      ]
    }
  },
  "schemaVersion": 1,
  "sdkVersion": "0.22.3",
  "streamFiles": [
    "wandb-history.jsonl",
    "wandb-summary.json"
  ],
  "upsertBucketVariableKeys": [
    "commit",
    "config",
    "debug",
    "description",
    "displayName",
    "entity",
    "groupName",
    "host",
    "id",
    "jobType",
    "name",
    "notes",
    "program",
    "project",
    "repo",
    "state",
    "summaryMetrics",
    "sweep",
    "tags"
  ],
  "upstreamOrigin": "https://api.wandb.ai"
} as const;
