// Generated by h200/stage_allocation/generate_contract.py; do not edit.
export const CAMPAIGN = {
  "allowedStates": [
    null,
    "running",
    "finished"
  ],
  "campaignId": "h200-imagenet100-stage-allocation-s501-v2",
  "entity": "daehwa",
  "graphqlEnvelopeKeys": {
    "CreateRunFiles": [
      "operationName",
      "query",
      "variables"
    ],
    "ProbeServerCapabilities": [
      "query",
      "variables"
    ],
    "RunResumeStatus": [
      "operationName",
      "query",
      "variables"
    ],
    "RunStoppedStatus": [
      "operationName",
      "query",
      "variables"
    ],
    "ServerFeaturesQuery": [
      "operationName",
      "query"
    ],
    "UpsertBucket": [
      "operationName",
      "query",
      "variables"
    ],
    "Viewer": [
      "query",
      "variables"
    ]
  },
  "graphqlOperations": {
    "CreateRunFiles": "66f378732e60ffebf606025796ebd6515971be93fae2716730ef9a0fe6532997",
    "ProbeServerCapabilities": "199320da83c03c5613aa66a759d333a32ebba1c44068a79f98be6733f249eae4",
    "RunResumeStatus": "a5605080f3769fa833cde5195012079fce1f2138f52377db5861d4c1b86a6082",
    "RunStoppedStatus": "d951e425fa91e971528ae94226cdc06b9d6dde7f07929d8548e9a4a4f9a323cc",
    "ServerFeaturesQuery": "4ebf7664b24d74a90fa96ce71f8616d9838f25bc5f8b0c41e4223bc0144a2991",
    "UpsertBucket": "a30f4b9373ef4d200d9e927fe21315320dc83fc409c70a7ed64201a2b107bf6d",
    "Viewer": "e5782f8ad76269e0104b45e78e82bc03efcc6783ec68299ac082de12c5475a33"
  },
  "group": "h200-imagenet100-stage-allocation-s501-v2",
  "manifestSha256": "68494cffc0471b349e73f882dc3638a7c9fb2fe3a5cebce09d6de223cb2b9c3c",
  "maxFileStreamBodyBytes": 10485760,
  "maxGraphqlBodyBytes": 1048576,
  "noVariableOperations": [
    "ProbeServerCapabilities",
    "Viewer",
    "ServerFeaturesQuery"
  ],
  "project": "alphabet2d-imagenet100-h200",
  "protocolVersion": "wandb-0.22.3-h200-imagenet100-stage-v2",
  "runFiles": [
    "config.yaml",
    "wandb-summary.json"
  ],
  "runsById": {
    "293d1058e82a1bba": {
      "displayName": "H200-I100-S501-11-K128-P128x4-D2223-FullSR7x1",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "35bdfc999b05a02f": {
      "displayName": "H200-I100-S501-01-K128-P128x4-D2222-Control",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "3d004b6bf5de5779": {
      "displayName": "H200-I100-S501-04-K128-P160-160-160-128-D2222",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "45c63e3ee821dd83": {
      "displayName": "H200-I100-S501-08-K128-P96x4-D2222",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "64ad47a6801015cf": {
      "displayName": "H200-I100-S501-05-K128-P160-160-160-96-D2222",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "69317f5ddd57f528": {
      "displayName": "H200-I100-S501-10-K128-P128x4-D2232-FullSR14x1",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "6f75b2daadc186da": {
      "displayName": "H200-I100-S501-09-K96-P128x4-D2222",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "8796a8e3ad94f895": {
      "displayName": "H200-I100-S501-03-K128-P128-160-160-128-D2222",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "9f8c7ecb05f34cf9": {
      "displayName": "H200-I100-S501-12-K128-P128x4-D2242-FullSR14x2",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "d16c7979e783d7b6": {
      "displayName": "H200-I100-S501-13-K128-P128x4-D2262-FullSR14x4",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "d4782711ffe66305": {
      "displayName": "H200-I100-stage-relay-permanent-canary-v2",
      "tags": [
        "H200",
        "ImageNet-100",
        "relay-canary",
        "authenticated"
      ]
    },
    "e89c9513212e8f7a": {
      "displayName": "H200-I100-S501-06-K128-P128-128-160-96-D2222",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "ea67e914c52b0174": {
      "displayName": "H200-I100-S501-07-K128-P96-128-160-96-D2222",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "f9644a12f47eca2a": {
      "displayName": "H200-I100-S501-02-K128-P128-128-160-128-D2222",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    }
  },
  "schemaVersion": 1,
  "sdkVersion": "0.22.3",
  "streamFiles": [
    "wandb-history.jsonl",
    "wandb-summary.json"
  ],
  "upsertBucketVariableKeys": [
    "commit",
    "config",
    "debug",
    "description",
    "displayName",
    "entity",
    "groupName",
    "host",
    "id",
    "jobType",
    "name",
    "notes",
    "program",
    "project",
    "repo",
    "state",
    "summaryMetrics",
    "sweep",
    "tags"
  ],
  "upstreamOrigin": "https://api.wandb.ai"
} as const;
