// Generated by h200/stage_allocation/generate_contract.py; do not edit.
export const CAMPAIGN = {
  "allowedStates": [
    null,
    "running",
    "finished"
  ],
  "campaignId": "h200-imagenet100-stage-allocation-s501-v1",
  "entity": "daehwa",
  "graphqlEnvelopeKeys": {
    "CreateRunFiles": [
      "operationName",
      "query",
      "variables"
    ],
    "ProbeServerCapabilities": [
      "query",
      "variables"
    ],
    "RunResumeStatus": [
      "operationName",
      "query",
      "variables"
    ],
    "RunStoppedStatus": [
      "operationName",
      "query",
      "variables"
    ],
    "ServerFeaturesQuery": [
      "operationName",
      "query"
    ],
    "UpsertBucket": [
      "operationName",
      "query",
      "variables"
    ],
    "Viewer": [
      "query",
      "variables"
    ]
  },
  "graphqlOperations": {
    "CreateRunFiles": "66f378732e60ffebf606025796ebd6515971be93fae2716730ef9a0fe6532997",
    "ProbeServerCapabilities": "199320da83c03c5613aa66a759d333a32ebba1c44068a79f98be6733f249eae4",
    "RunResumeStatus": "a5605080f3769fa833cde5195012079fce1f2138f52377db5861d4c1b86a6082",
    "RunStoppedStatus": "d951e425fa91e971528ae94226cdc06b9d6dde7f07929d8548e9a4a4f9a323cc",
    "ServerFeaturesQuery": "4ebf7664b24d74a90fa96ce71f8616d9838f25bc5f8b0c41e4223bc0144a2991",
    "UpsertBucket": "a30f4b9373ef4d200d9e927fe21315320dc83fc409c70a7ed64201a2b107bf6d",
    "Viewer": "e5782f8ad76269e0104b45e78e82bc03efcc6783ec68299ac082de12c5475a33"
  },
  "group": "h200-imagenet100-stage-allocation-s501-v1",
  "manifestSha256": "190a8cc09631a6e126515349c915da37674b93d2679f541d5ca0615444fc81e4",
  "maxFileStreamBodyBytes": 8388608,
  "maxGraphqlBodyBytes": 1048576,
  "noVariableOperations": [
    "ProbeServerCapabilities",
    "Viewer",
    "ServerFeaturesQuery"
  ],
  "project": "alphabet2d-imagenet100-h200",
  "protocolVersion": "wandb-0.22.3-h200-imagenet100-stage-v1",
  "runFiles": [
    "config.yaml",
    "wandb-summary.json"
  ],
  "runsById": {
    "01d960b0acf7c9fb": {
      "displayName": "H200-I100-S501-10-K128-P128x4-D2223-FullSR7x1",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "3426284ea3681eb4": {
      "displayName": "H200-I100-S501-01-K128-P128-128-160-128-D2222",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "35ad53355fb2b883": {
      "displayName": "H200-I100-S501-12-K128-P128x4-D2262-FullSR14x4",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "5e552b9655fab181": {
      "displayName": "H200-I100-stage-relay-permanent-canary-v1",
      "tags": [
        "H200",
        "ImageNet-100",
        "relay-canary",
        "authenticated"
      ]
    },
    "850c9e5a5fb8ac92": {
      "displayName": "H200-I100-S501-06-K128-P96-128-160-96-D2222",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "881c88dad9b52570": {
      "displayName": "H200-I100-S501-02-K128-P128-160-160-128-D2222",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "8b3f8293a6fb2f30": {
      "displayName": "H200-I100-S501-11-K128-P128x4-D2242-FullSR14x2",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "98a4b9ffd80fb5f1": {
      "displayName": "H200-I100-S501-04-K128-P160-160-160-96-D2222",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "aa7f7462e16b3c44": {
      "displayName": "H200-I100-S501-07-K128-P96x4-D2222",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "c8c9bc578a46cf15": {
      "displayName": "H200-I100-S501-08-K96-P128x4-D2222",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "d4f16c020e52a3b8": {
      "displayName": "H200-I100-S501-05-K128-P128-128-160-96-D2222",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "d9b5ae209a206d7f": {
      "displayName": "H200-I100-S501-09-K128-P128x4-D2232-FullSR14x1",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    },
    "f07284e68c570274": {
      "displayName": "H200-I100-S501-03-K128-P160-160-160-128-D2222",
      "tags": [
        "H200",
        "ImageNet-100",
        "stage-allocation",
        "seed501",
        "authenticated"
      ]
    }
  },
  "schemaVersion": 1,
  "sdkVersion": "0.22.3",
  "streamFiles": [
    "wandb-history.jsonl",
    "wandb-summary.json"
  ],
  "upsertBucketVariableKeys": [
    "commit",
    "config",
    "debug",
    "description",
    "displayName",
    "entity",
    "groupName",
    "host",
    "id",
    "jobType",
    "name",
    "notes",
    "program",
    "project",
    "repo",
    "state",
    "summaryMetrics",
    "sweep",
    "tags"
  ],
  "upstreamOrigin": "https://api.wandb.ai"
} as const;
