// Generated by h200/generate_campaign.py; do not edit.
export const CAMPAIGN = {
  "allowedStates": [
    null,
    "running",
    "finished"
  ],
  "campaignId": "h200-imagenet1k-k3-rmsmatch-pg-ab-v3",
  "entity": "daehwa",
  "graphqlEnvelopeKeys": {
    "CreateRunFiles": [
      "operationName",
      "query",
      "variables"
    ],
    "ProbeServerCapabilities": [
      "query",
      "variables"
    ],
    "RunResumeStatus": [
      "operationName",
      "query",
      "variables"
    ],
    "RunStoppedStatus": [
      "operationName",
      "query",
      "variables"
    ],
    "ServerFeaturesQuery": [
      "operationName",
      "query"
    ],
    "UpsertBucket": [
      "operationName",
      "query",
      "variables"
    ],
    "Viewer": [
      "query",
      "variables"
    ]
  },
  "graphqlOperations": {
    "CreateRunFiles": "66f378732e60ffebf606025796ebd6515971be93fae2716730ef9a0fe6532997",
    "ProbeServerCapabilities": "199320da83c03c5613aa66a759d333a32ebba1c44068a79f98be6733f249eae4",
    "RunResumeStatus": "a5605080f3769fa833cde5195012079fce1f2138f52377db5861d4c1b86a6082",
    "RunStoppedStatus": "d951e425fa91e971528ae94226cdc06b9d6dde7f07929d8548e9a4a4f9a323cc",
    "ServerFeaturesQuery": "4ebf7664b24d74a90fa96ce71f8616d9838f25bc5f8b0c41e4223bc0144a2991",
    "UpsertBucket": "a30f4b9373ef4d200d9e927fe21315320dc83fc409c70a7ed64201a2b107bf6d",
    "Viewer": "e5782f8ad76269e0104b45e78e82bc03efcc6783ec68299ac082de12c5475a33"
  },
  "group": "h200-imagenet1k-k3-rmsmatch-pg-ab-v3",
  "manifestSha256": "550e723b138fa9b1c5a575dd475f8741276f7b3b2220a105dc630aa565c3e216",
  "maxFileStreamBodyBytes": 8388608,
  "maxGraphqlBodyBytes": 1048576,
  "noVariableOperations": [
    "ProbeServerCapabilities",
    "Viewer",
    "ServerFeaturesQuery"
  ],
  "project": "alphabet2d-imagenet1k-h200",
  "protocolVersion": "wandb-0.22.3-h200-v3",
  "runFiles": [
    "config.yaml",
    "wandb-summary.json"
  ],
  "runsById": {
    "56038182b4beb318": {
      "displayName": "H200-I1K-PG-s501-v3",
      "tags": [
        "H200",
        "ImageNet-1K",
        "PG-ablation",
        "authenticated"
      ]
    },
    "bcc1f482f4fc98f4": {
      "displayName": "H200-I1K-NoPG-s501-v3",
      "tags": [
        "H200",
        "ImageNet-1K",
        "PG-ablation",
        "authenticated"
      ]
    },
    "bfb34528d82b9920": {
      "displayName": "H200-relay-permanent-canary-v3",
      "tags": [
        "H200",
        "ImageNet-1K",
        "relay-canary",
        "authenticated"
      ]
    }
  },
  "schemaVersion": 3,
  "sdkVersion": "0.22.3",
  "streamFiles": [
    "wandb-history.jsonl",
    "wandb-summary.json"
  ],
  "upsertBucketVariableKeys": [
    "commit",
    "config",
    "debug",
    "description",
    "displayName",
    "entity",
    "groupName",
    "host",
    "id",
    "jobType",
    "name",
    "notes",
    "program",
    "project",
    "repo",
    "state",
    "summaryMetrics",
    "sweep",
    "tags"
  ],
  "upstreamOrigin": "https://api.wandb.ai"
} as const;
