/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false` (hash: db388946735ada681e9aa58763a78f06)
interface __BaseEnv_Env {
	RELAY_RATE_LIMITER: RateLimit;
	WANDB_API_KEY: string;
	ALLOWED_EGRESS_IPS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WANDB_API_KEY" | "ALLOWED_EGRESS_IPS">> {}
}
