// Generated by h200/baselines/generate_wandb_contract.py; do not edit.
export const CAMPAIGN = {
  "allowedStates": [
    null,
    "running",
    "finished"
  ],
  "campaignId": "h200-imagenet1k-moga-emo-100ep-s501-v2",
  "entity": "daehwa",
  "graphqlEnvelopeKeys": {
    "CreateRunFiles": [
      "operationName",
      "query",
      "variables"
    ],
    "ProbeServerCapabilities": [
      "query",
      "variables"
    ],
    "RunResumeStatus": [
      "operationName",
      "query",
      "variables"
    ],
    "RunStoppedStatus": [
      "operationName",
      "query",
      "variables"
    ],
    "ServerFeaturesQuery": [
      "operationName",
      "query"
    ],
    "UpsertBucket": [
      "operationName",
      "query",
      "variables"
    ],
    "Viewer": [
      "query",
      "variables"
    ]
  },
  "graphqlOperations": {
    "CreateRunFiles": "66f378732e60ffebf606025796ebd6515971be93fae2716730ef9a0fe6532997",
    "ProbeServerCapabilities": "199320da83c03c5613aa66a759d333a32ebba1c44068a79f98be6733f249eae4",
    "RunResumeStatus": "a5605080f3769fa833cde5195012079fce1f2138f52377db5861d4c1b86a6082",
    "RunStoppedStatus": "d951e425fa91e971528ae94226cdc06b9d6dde7f07929d8548e9a4a4f9a323cc",
    "ServerFeaturesQuery": "4ebf7664b24d74a90fa96ce71f8616d9838f25bc5f8b0c41e4223bc0144a2991",
    "UpsertBucket": "a30f4b9373ef4d200d9e927fe21315320dc83fc409c70a7ed64201a2b107bf6d",
    "Viewer": "e5782f8ad76269e0104b45e78e82bc03efcc6783ec68299ac082de12c5475a33"
  },
  "group": "h200-imagenet1k-moga-emo-100ep-s501-v2",
  "manifestSha256": "bfd46cad39be839592d6b5adad12beff65a4be993708ba729e1fbcc2e32edbc3",
  "maxFileStreamBodyBytes": 8388608,
  "maxGraphqlBodyBytes": 1048576,
  "noVariableOperations": [
    "ProbeServerCapabilities",
    "Viewer",
    "ServerFeaturesQuery"
  ],
  "project": "alphabet2d-imagenet1k-h200-baselines",
  "protocolVersion": "wandb-0.22.3-h200-baselines-v1",
  "runFiles": [
    "config.yaml",
    "wandb-summary.json"
  ],
  "runsById": {
    "0166f1935c8fd1d5": {
      "displayName": "H200-BL-tinynext_s-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "0a6dc2239978bca5": {
      "displayName": "H200-BL-mobileone_s1-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "0d2555a53f588405": {
      "displayName": "H200-BL-efficientformerv2_s0-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "10d502fd0d931aa3": {
      "displayName": "H200-BL-sret_tiny-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "1726a3a38b918664": {
      "displayName": "H200-BL-tinynext_s-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "1f72c4a0503849cb": {
      "displayName": "H200-BL-mobilevitv2_100-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "229f5c85bcbce281": {
      "displayName": "H200-BL-tinynext_s-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "25108d1c01557396": {
      "displayName": "H200-MIG1-BL-mambaout_femto-s509",
      "tags": [
        "H200",
        "MIG-1g.18gb",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "seed509"
      ]
    },
    "26f109ae80471f86": {
      "displayName": "H200-LNet-I1K-K96-P128x4-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "LNet",
        "K96",
        "P128x4",
        "D2262",
        "100ep",
        "seed521"
      ]
    },
    "28fdca0ac0c09d0c": {
      "displayName": "H200-MIG1-BL-mambaout_femto-s501",
      "tags": [
        "H200",
        "MIG-1g.18gb",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "seed501"
      ]
    },
    "2916bac3cc133f3f": {
      "displayName": "H200-MIG1-BL-tinyvim_s-s509",
      "tags": [
        "H200",
        "MIG-1g.18gb",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "seed509"
      ]
    },
    "291db6703a93660c": {
      "displayName": "H200-BL-parc_net_s-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "29420bf188b605c0": {
      "displayName": "H200-BL-mobileone_s1-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "29d068e90904bd6c": {
      "displayName": "H200-BL-emov2_2m-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "2f2f995922b5c122": {
      "displayName": "H200-BL-emov2_1m-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "30740f8eb5fbac48": {
      "displayName": "H200-BL-mobilevitv2_100-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "30d48827e2911f2a": {
      "displayName": "H200-BL-efficientmod_xxs-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "32cf8d845e17e2fb": {
      "displayName": "H200-MIG1-BL-mambaout_femto-s521",
      "tags": [
        "H200",
        "MIG-1g.18gb",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "seed521"
      ]
    },
    "3a8ade548d469ee1": {
      "displayName": "H200-BL-parc_net_s-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "3b515fadaa6af21b": {
      "displayName": "H200-BL-sret_tiny-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "462b0560fd64a95d": {
      "displayName": "H200-BL-emov2_1m-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "47624db7775ef88d": {
      "displayName": "H200-BL-mobilevitv2_075-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "4a8d135549aa68a9": {
      "displayName": "H200-BL-fastvit_t8-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "4c533d92bc21439a": {
      "displayName": "H200-BL-convnextv2_atto-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "4e4bfae5b7e8e71c": {
      "displayName": "H200-BL-parc_net_xs-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "53332014b74f7a45": {
      "displayName": "H200-baseline-relay-permanent-canary-v1",
      "tags": [
        "H200",
        "ImageNet-1K",
        "relay-canary",
        "ip-scoped-untrusted"
      ]
    },
    "6f1f49d367eb7860": {
      "displayName": "H200-BL-uniconvnet_a-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "7267114d86cd96a0": {
      "displayName": "H200-BL-efficientmod_xxs-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "748c7a87ef0b5c7a": {
      "displayName": "H200-MIG1-BL-efficientvim_m1-s501",
      "tags": [
        "H200",
        "MIG-1g.18gb",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "seed501"
      ]
    },
    "762c311e1e37a309": {
      "displayName": "H200-BL-parc_net_xs-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "7672d03f5002cd2e": {
      "displayName": "H200-BL-tinynext_m-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "7aac4714b8447917": {
      "displayName": "H200-BL-mobileone_s0-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "81780d43c245cf5d": {
      "displayName": "H200-BL-convnextv2_atto-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "836a6acc82157f1d": {
      "displayName": "H200-BL-efficientformerv2_s0-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "84f6775cae126d9a": {
      "displayName": "H200-BL-mobileone_s0-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "8720104de02377ea": {
      "displayName": "H200-BL-mobilevitv2_050-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "8c55b51baabe45a5": {
      "displayName": "H200-BL-emov2_2m-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "8c8c458658c29f77": {
      "displayName": "H200-BL-uniconvnet_a-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "8d69c30e365d5d8c": {
      "displayName": "H200-BL-mobileone_s0-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "959602bfc72dd2d7": {
      "displayName": "H200-BL-tinynext_m-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "9a3fcfa42cd92a42": {
      "displayName": "H200-BL-parc_net_s-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "9ed1e2bc3cb14347": {
      "displayName": "H200-BL-sret_tiny-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "a2b0a3722dbc344a": {
      "displayName": "H200-BL-fastvit_t8-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "a6175dbc6691b0bc": {
      "displayName": "H200-BL-fastvit_t8-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "a72af23a31e0d90b": {
      "displayName": "H200-BL-emov2_1m-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "aba9ea70ffcded6c": {
      "displayName": "H200-BL-swiftformer_xs-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "ac16df3bf18b8aaf": {
      "displayName": "H200-BL-tinynext_t-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "acbf8883480b5cfe": {
      "displayName": "H200-BL-parc_net_xs-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "ad90c8e9fa1ccb52": {
      "displayName": "H200-MIG1-BL-efficientvim_m1-s509",
      "tags": [
        "H200",
        "MIG-1g.18gb",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "seed509"
      ]
    },
    "ae0737afed233e48": {
      "displayName": "H200-BL-moganet_xt-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "bb8647fb14ae22d4": {
      "displayName": "H200-BL-swiftformer_xs-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "bc4b91c4837d1eac": {
      "displayName": "H200-BL-mobilevitv2_100-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "c461a36a830b448d": {
      "displayName": "H200-BL-mobilevitv2_075-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "c5b7d5aa7630d287": {
      "displayName": "H200-LNet-I1K-K96-P128x4-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "LNet",
        "K96",
        "P128x4",
        "D2262",
        "100ep",
        "seed509"
      ]
    },
    "c5fabb6cf5fc193b": {
      "displayName": "H200-BL-mobileone_s1-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "c83df32df56a613c": {
      "displayName": "H200-BL-moganet_xt-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "c8d39bbc7fa870d0": {
      "displayName": "H200-MIG1-BL-tinyvim_s-s501",
      "tags": [
        "H200",
        "MIG-1g.18gb",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "seed501"
      ]
    },
    "d8a0e86658d1e5fa": {
      "displayName": "H200-BL-moganet_xt-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "d92c7b9be8cf191c": {
      "displayName": "H200-BL-mobilevitv2_075-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "da5e56f457ef3212": {
      "displayName": "H200-BL-convnextv2_atto-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "e339a3d0ac3f739e": {
      "displayName": "H200-MIG1-BL-tinyvim_s-s521",
      "tags": [
        "H200",
        "MIG-1g.18gb",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "seed521"
      ]
    },
    "e37d6d78476d5ca5": {
      "displayName": "H200-MIG1-BL-efficientvim_m1-s521",
      "tags": [
        "H200",
        "MIG-1g.18gb",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "seed521"
      ]
    },
    "e611233788333433": {
      "displayName": "H200-BL-tinynext_t-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "e639a6ac6a6597e9": {
      "displayName": "H200-BL-efficientformerv2_s0-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "eb18940bc1a0f468": {
      "displayName": "H200-BL-uniconvnet_a-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "ec9d50f84bae2059": {
      "displayName": "H200-BL-mobilevitv2_050-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "ef506f63c39328f7": {
      "displayName": "H200-BL-tinynext_t-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "f1085f6c9dd880a6": {
      "displayName": "H200-BL-mobilevitv2_050-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "f81fb80e5b6c5375": {
      "displayName": "H200-BL-emov2_2m-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "f86fed2601b0626f": {
      "displayName": "H200-BL-efficientmod_xxs-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "f9b08e45fe52273f": {
      "displayName": "H200-BL-swiftformer_xs-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "fe5ed895bed23f60": {
      "displayName": "H200-BL-tinynext_m-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    }
  },
  "schemaVersion": 1,
  "sdkVersion": "0.22.3",
  "streamFiles": [
    "wandb-history.jsonl",
    "wandb-summary.json"
  ],
  "upsertBucketVariableKeys": [
    "commit",
    "config",
    "debug",
    "description",
    "displayName",
    "entity",
    "groupName",
    "host",
    "id",
    "jobType",
    "name",
    "notes",
    "program",
    "project",
    "repo",
    "state",
    "summaryMetrics",
    "sweep",
    "tags"
  ],
  "upstreamOrigin": "https://api.wandb.ai"
} as const;
