// Generated by h200/baselines/generate_wandb_contract.py; do not edit.
export const CAMPAIGN = {
  "allowedStates": [
    null,
    "running",
    "finished"
  ],
  "campaignId": "h200-imagenet1k-moga-emo-100ep-s501-v1",
  "entity": "daehwa",
  "graphqlEnvelopeKeys": {
    "CreateRunFiles": [
      "operationName",
      "query",
      "variables"
    ],
    "ProbeServerCapabilities": [
      "query",
      "variables"
    ],
    "RunResumeStatus": [
      "operationName",
      "query",
      "variables"
    ],
    "RunStoppedStatus": [
      "operationName",
      "query",
      "variables"
    ],
    "ServerFeaturesQuery": [
      "operationName",
      "query"
    ],
    "UpsertBucket": [
      "operationName",
      "query",
      "variables"
    ],
    "Viewer": [
      "query",
      "variables"
    ]
  },
  "graphqlOperations": {
    "CreateRunFiles": "66f378732e60ffebf606025796ebd6515971be93fae2716730ef9a0fe6532997",
    "ProbeServerCapabilities": "199320da83c03c5613aa66a759d333a32ebba1c44068a79f98be6733f249eae4",
    "RunResumeStatus": "a5605080f3769fa833cde5195012079fce1f2138f52377db5861d4c1b86a6082",
    "RunStoppedStatus": "d951e425fa91e971528ae94226cdc06b9d6dde7f07929d8548e9a4a4f9a323cc",
    "ServerFeaturesQuery": "4ebf7664b24d74a90fa96ce71f8616d9838f25bc5f8b0c41e4223bc0144a2991",
    "UpsertBucket": "a30f4b9373ef4d200d9e927fe21315320dc83fc409c70a7ed64201a2b107bf6d",
    "Viewer": "e5782f8ad76269e0104b45e78e82bc03efcc6783ec68299ac082de12c5475a33"
  },
  "group": "h200-imagenet1k-moga-emo-100ep-s501-v1",
  "manifestSha256": "5c2c873130a4a009a6ae65c46a431e71bcdc3bbfea31ed4341e167d649fffe36",
  "maxFileStreamBodyBytes": 8388608,
  "maxGraphqlBodyBytes": 1048576,
  "noVariableOperations": [
    "ProbeServerCapabilities",
    "Viewer",
    "ServerFeaturesQuery"
  ],
  "project": "alphabet2d-imagenet1k-h200-baselines",
  "protocolVersion": "wandb-0.22.3-h200-baselines-v1",
  "runFiles": [
    "config.yaml",
    "wandb-summary.json"
  ],
  "runsById": {
    "03f4dbf9d01a622b": {
      "displayName": "H200-BL-convnextv2_atto-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "0a4922a984bbe16d": {
      "displayName": "H200-BL-mobilevitv2_075-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "0cd578250f5ce8a1": {
      "displayName": "H200-BL-tinynext_s-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "14415b34b2d11908": {
      "displayName": "H200-BL-mobilevitv2_075-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "163de600e660c7ce": {
      "displayName": "H200-baseline-relay-permanent-canary-v1",
      "tags": [
        "H200",
        "ImageNet-1K",
        "relay-canary",
        "ip-scoped-untrusted"
      ]
    },
    "1b47e6a7d02d5dbc": {
      "displayName": "H200-BL-tinynext_m-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "1dcb9cdcbf201dbc": {
      "displayName": "H200-BL-mobilevitv2_050-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "27c1e8dca8e41d7f": {
      "displayName": "H200-BL-swiftformer_xs-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "2c613d8db0ca9064": {
      "displayName": "H200-BL-mobilevitv2_100-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "2ef6e40cfc4f1ff7": {
      "displayName": "H200-BL-parc_net_s-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "335401cc6bb7f480": {
      "displayName": "H200-BL-mobileone_s1-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "384e7c8150ff6073": {
      "displayName": "H200-BL-swiftformer_xs-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "39c91dcd7c84f98c": {
      "displayName": "H200-BL-tinynext_m-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "3b631687ea362341": {
      "displayName": "H200-BL-parc_net_xs-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "3de1cedfb9aa3e26": {
      "displayName": "H200-BL-mobilevitv2_050-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "4357fb9083633d70": {
      "displayName": "H200-BL-moganet_xt-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "437dc4b7625407bf": {
      "displayName": "H200-BL-convnextv2_atto-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "4434e4f00e3d1151": {
      "displayName": "H200-BL-moganet_xt-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "44fb05537240ea81": {
      "displayName": "H200-BL-emov2_2m-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "46d47d8589d8f519": {
      "displayName": "H200-BL-sret_tiny-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "4708941a0f6865b7": {
      "displayName": "H200-BL-parc_net_s-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "4aa1c15b259aee69": {
      "displayName": "H200-BL-emov2_1m-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "4d66f8afed44103d": {
      "displayName": "H200-BL-efficientformerv2_s0-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "53fba8585abcd3f2": {
      "displayName": "H200-BL-tinynext_m-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "583a476ae9ec63c6": {
      "displayName": "H200-BL-mobileone_s1-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "587fed2bdb52102d": {
      "displayName": "H200-BL-parc_net_xs-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "5ca96f806c9e1866": {
      "displayName": "H200-BL-mobileone_s1-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "5f6af93b1df16c63": {
      "displayName": "H200-BL-efficientformerv2_s0-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "627645185351867d": {
      "displayName": "H200-BL-swiftformer_xs-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "64e6136f18811964": {
      "displayName": "H200-BL-mobileone_s0-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "65441d1262888f09": {
      "displayName": "H200-BL-uniconvnet_a-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "6b42eea4fcaac9ba": {
      "displayName": "H200-BL-fastvit_t8-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "72941bf16b6f5c43": {
      "displayName": "H200-BL-mobilevitv2_075-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "75104bc8ec379dbf": {
      "displayName": "H200-BL-mobilevitv2_100-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "7fa155242db7ee17": {
      "displayName": "H200-BL-tinynext_t-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "855b36f1ae765e08": {
      "displayName": "H200-BL-mobileone_s0-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "87122004adb4ade9": {
      "displayName": "H200-BL-uniconvnet_a-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "89eeacbe865d02a9": {
      "displayName": "H200-BL-mobilevitv2_100-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "8a83c39f29f61746": {
      "displayName": "H200-BL-tinynext_s-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "8ae75d9c00c00ebd": {
      "displayName": "H200-BL-uniconvnet_a-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "8d58eb8dc4dce718": {
      "displayName": "H200-BL-convnextv2_atto-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "8f2c0706009f17a1": {
      "displayName": "H200-BL-tinynext_s-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "9065a06c2db48fd5": {
      "displayName": "H200-BL-efficientformerv2_s0-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "a8a98f0f98d4d395": {
      "displayName": "H200-BL-sret_tiny-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "aa4f796667254c11": {
      "displayName": "H200-BL-emov2_1m-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "b0d98a46fea59a9f": {
      "displayName": "H200-BL-moganet_xt-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "b6904aaf3d05a0f5": {
      "displayName": "H200-BL-sret_tiny-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "bfdfa28348473944": {
      "displayName": "H200-BL-efficientmod_xxs-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "c2a9e577d69e6d92": {
      "displayName": "H200-BL-parc_net_s-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "c5642da87314fc10": {
      "displayName": "H200-BL-mobilevitv2_050-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "c5cb518e0405f05a": {
      "displayName": "H200-BL-fastvit_t8-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "c927330109f33fa4": {
      "displayName": "H200-BL-mobileone_s0-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "cd62e3bec09b4c83": {
      "displayName": "H200-BL-emov2_1m-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "da3754c90541dc99": {
      "displayName": "H200-BL-parc_net_xs-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "dcb6b9f331fcf544": {
      "displayName": "H200-BL-tinynext_t-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "e2b61be87d4ea46b": {
      "displayName": "H200-BL-emov2_2m-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "ebe62fa246ee9fd9": {
      "displayName": "H200-BL-efficientmod_xxs-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "efc174403c29aaba": {
      "displayName": "H200-BL-efficientmod_xxs-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "f2506a2c49cec0ff": {
      "displayName": "H200-BL-fastvit_t8-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "f54f8dc3cfeffdb6": {
      "displayName": "H200-BL-tinynext_t-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "fbb5f7f977bcdf93": {
      "displayName": "H200-BL-emov2_2m-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "100ep",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    }
  },
  "schemaVersion": 1,
  "sdkVersion": "0.22.3",
  "streamFiles": [
    "wandb-history.jsonl",
    "wandb-summary.json"
  ],
  "upsertBucketVariableKeys": [
    "commit",
    "config",
    "debug",
    "description",
    "displayName",
    "entity",
    "groupName",
    "host",
    "id",
    "jobType",
    "name",
    "notes",
    "program",
    "project",
    "repo",
    "state",
    "summaryMetrics",
    "sweep",
    "tags"
  ],
  "upstreamOrigin": "https://api.wandb.ai"
} as const;
