// Generated by h200/baselines/generate_wandb_contract.py; do not edit.
export const CAMPAIGN = {
  "allowedStates": [
    null,
    "running",
    "finished"
  ],
  "campaignId": "h200-imagenet1k-matched-baselines-300ep-v1",
  "entity": "daehwa",
  "graphqlEnvelopeKeys": {
    "CreateRunFiles": [
      "operationName",
      "query",
      "variables"
    ],
    "ProbeServerCapabilities": [
      "query",
      "variables"
    ],
    "RunResumeStatus": [
      "operationName",
      "query",
      "variables"
    ],
    "RunStoppedStatus": [
      "operationName",
      "query",
      "variables"
    ],
    "ServerFeaturesQuery": [
      "operationName",
      "query"
    ],
    "UpsertBucket": [
      "operationName",
      "query",
      "variables"
    ],
    "Viewer": [
      "query",
      "variables"
    ]
  },
  "graphqlOperations": {
    "CreateRunFiles": "66f378732e60ffebf606025796ebd6515971be93fae2716730ef9a0fe6532997",
    "ProbeServerCapabilities": "199320da83c03c5613aa66a759d333a32ebba1c44068a79f98be6733f249eae4",
    "RunResumeStatus": "a5605080f3769fa833cde5195012079fce1f2138f52377db5861d4c1b86a6082",
    "RunStoppedStatus": "d951e425fa91e971528ae94226cdc06b9d6dde7f07929d8548e9a4a4f9a323cc",
    "ServerFeaturesQuery": "4ebf7664b24d74a90fa96ce71f8616d9838f25bc5f8b0c41e4223bc0144a2991",
    "UpsertBucket": "a30f4b9373ef4d200d9e927fe21315320dc83fc409c70a7ed64201a2b107bf6d",
    "Viewer": "e5782f8ad76269e0104b45e78e82bc03efcc6783ec68299ac082de12c5475a33"
  },
  "group": "h200-imagenet1k-matched-baselines-300ep-v1",
  "manifestSha256": "36800df3411f027aaff3d87fcf9c5f164f90f2e5160c12bc9116fa74beb79bff",
  "maxFileStreamBodyBytes": 8388608,
  "maxGraphqlBodyBytes": 1048576,
  "noVariableOperations": [
    "ProbeServerCapabilities",
    "Viewer",
    "ServerFeaturesQuery"
  ],
  "project": "alphabet2d-imagenet1k-h200-baselines",
  "protocolVersion": "wandb-0.22.3-h200-baselines-v1",
  "runFiles": [
    "config.yaml",
    "wandb-summary.json"
  ],
  "runsById": {
    "03ef12a234901ca8": {
      "displayName": "H200-BL-mobilevitv2_100-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "0455ab8d70c4fc73": {
      "displayName": "H200-BL-mobilevitv2_050-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "0810dc621cbd5896": {
      "displayName": "H200-BL-parc_net_xs-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "0f6102b7fdae56b0": {
      "displayName": "H200-BL-efficientformerv2_s0-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "127ccf596b4e164e": {
      "displayName": "H200-BL-mobilevitv2_075-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "12dfa7f550aebccf": {
      "displayName": "H200-BL-fastvit_t8-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "171f3a55f017f8dc": {
      "displayName": "H200-BL-mobilevitv2_050-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "18a6890693aca596": {
      "displayName": "H200-BL-emov2_1m-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "1a30db55813875bc": {
      "displayName": "H200-BL-convnextv2_atto-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "1f43bcf17af33125": {
      "displayName": "H200-BL-mobileone_s1-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "21c08ec6b6860b34": {
      "displayName": "H200-BL-uniconvnet_a-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "251ab1f299d905c7": {
      "displayName": "H200-BL-convnextv2_atto-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "255c4605c67493e2": {
      "displayName": "H200-BL-efficientformerv2_s0-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "26a70e360cd4852b": {
      "displayName": "H200-BL-mobileone_s0-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "2e65634c0234291b": {
      "displayName": "H200-BL-tinynext_s-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "2eb1b28913ad4e20": {
      "displayName": "H200-BL-parc_net_xs-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "34849a180916920f": {
      "displayName": "H200-BL-tinynext_m-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "3a01226a5fd142d1": {
      "displayName": "H200-BL-emov2_1m-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "416822738617f28c": {
      "displayName": "H200-BL-tinynext_t-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "4742361374830d49": {
      "displayName": "H200-BL-uniconvnet_a-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "47cd995a86ed33e4": {
      "displayName": "H200-BL-moganet_xt-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "4ae53371396f78bd": {
      "displayName": "H200-BL-fastvit_t8-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "5ad32819b4bf3d79": {
      "displayName": "H200-BL-mobilevitv2_100-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "5b12f695d0a4e0bb": {
      "displayName": "H200-BL-mobilevitv2_050-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "68799cc79cc77ae2": {
      "displayName": "H200-BL-mobilevitv2_100-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "6b5bdeef4f082f79": {
      "displayName": "H200-BL-parc_net_s-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "7176e3a19f0e827d": {
      "displayName": "H200-BL-sret_tiny-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "7251dd34046b87f7": {
      "displayName": "H200-BL-mobileone_s0-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "75ca145fd808168a": {
      "displayName": "H200-BL-emov2_1m-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "769fdaf77641f0e6": {
      "displayName": "H200-BL-mobilevitv2_075-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "79cf507e2723e37b": {
      "displayName": "H200-BL-convnextv2_atto-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "7c86791753f52ed9": {
      "displayName": "H200-BL-mobileone_s1-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "7c9c2c35cbae3430": {
      "displayName": "H200-BL-efficientmod_xxs-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "8140bbdc213315f9": {
      "displayName": "H200-BL-moganet_xt-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "87bffc25ed988a99": {
      "displayName": "H200-BL-sret_tiny-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "8db3edade4b35307": {
      "displayName": "H200-BL-moganet_xt-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "93742abf6c0d35e5": {
      "displayName": "H200-BL-tinynext_m-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "98862c08a34cadb3": {
      "displayName": "H200-BL-mobileone_s1-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "a29df2ebe58dd537": {
      "displayName": "H200-BL-efficientformerv2_s0-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "acc9a0a867719565": {
      "displayName": "H200-BL-parc_net_s-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "b705ea92792f5144": {
      "displayName": "H200-BL-uniconvnet_a-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "ba0ed4b351952603": {
      "displayName": "H200-BL-parc_net_s-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "baaa3354d8ae90e9": {
      "displayName": "H200-BL-mobilevitv2_075-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "bb16aeeb9958d886": {
      "displayName": "H200-BL-tinynext_s-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "be1459049e118d12": {
      "displayName": "H200-BL-tinynext_s-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "c03f9d732abf05fc": {
      "displayName": "H200-BL-mobileone_s0-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "c0c95c5594113277": {
      "displayName": "H200-BL-swiftformer_xs-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "c194f53c98ece890": {
      "displayName": "H200-BL-fastvit_t8-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "c9d6e4bcee921495": {
      "displayName": "H200-BL-tinynext_t-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "ccab54dc7cd1f8a7": {
      "displayName": "H200-baseline-relay-permanent-canary-v1",
      "tags": [
        "H200",
        "ImageNet-1K",
        "relay-canary",
        "ip-scoped-untrusted"
      ]
    },
    "ccad0b92f9ec219e": {
      "displayName": "H200-BL-tinynext_m-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "ce71e95fab08c87e": {
      "displayName": "H200-BL-efficientmod_xxs-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "d6b83936ad198c5b": {
      "displayName": "H200-BL-emov2_2m-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "d79b2b972da63bd5": {
      "displayName": "H200-BL-parc_net_xs-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "d7abdb58ddfd8069": {
      "displayName": "H200-BL-emov2_2m-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "e4ce497ae71e6a8d": {
      "displayName": "H200-BL-swiftformer_xs-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "e5a1789ea3d52b24": {
      "displayName": "H200-BL-efficientmod_xxs-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "e694f056953490af": {
      "displayName": "H200-BL-sret_tiny-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "e8acdb1d21120326": {
      "displayName": "H200-BL-tinynext_t-s501",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "eac2f3c003d74153": {
      "displayName": "H200-BL-swiftformer_xs-s521",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    },
    "ec2a199ef5d9fb9c": {
      "displayName": "H200-BL-emov2_2m-s509",
      "tags": [
        "H200",
        "ImageNet-1K",
        "matched-baseline",
        "three-seed",
        "ip-scoped-untrusted"
      ]
    }
  },
  "schemaVersion": 1,
  "sdkVersion": "0.22.3",
  "streamFiles": [
    "wandb-history.jsonl",
    "wandb-summary.json"
  ],
  "upsertBucketVariableKeys": [
    "commit",
    "config",
    "debug",
    "description",
    "displayName",
    "entity",
    "groupName",
    "host",
    "id",
    "jobType",
    "name",
    "notes",
    "program",
    "project",
    "repo",
    "state",
    "summaryMetrics",
    "sweep",
    "tags"
  ],
  "upstreamOrigin": "https://api.wandb.ai"
} as const;
