// Generated by h200/cub200/generate_relay.py
export const CAMPAIGN = {
  "allowedStates": [
    null,
    "running",
    "finished"
  ],
  "campaignId": "cub200-scratch-100ep-lee-v1",
  "entity": "daehwa",
  "graphqlEnvelopeKeys": {
    "CreateRunFiles": [
      "operationName",
      "query",
      "variables"
    ],
    "ProbeServerCapabilities": [
      "query",
      "variables"
    ],
    "RunResumeStatus": [
      "operationName",
      "query",
      "variables"
    ],
    "RunStoppedStatus": [
      "operationName",
      "query",
      "variables"
    ],
    "ServerFeaturesQuery": [
      "operationName",
      "query"
    ],
    "UpsertBucket": [
      "operationName",
      "query",
      "variables"
    ],
    "Viewer": [
      "query",
      "variables"
    ]
  },
  "graphqlOperations": {
    "CreateRunFiles": "66f378732e60ffebf606025796ebd6515971be93fae2716730ef9a0fe6532997",
    "ProbeServerCapabilities": "199320da83c03c5613aa66a759d333a32ebba1c44068a79f98be6733f249eae4",
    "RunResumeStatus": "a5605080f3769fa833cde5195012079fce1f2138f52377db5861d4c1b86a6082",
    "RunStoppedStatus": "d951e425fa91e971528ae94226cdc06b9d6dde7f07929d8548e9a4a4f9a323cc",
    "ServerFeaturesQuery": "4ebf7664b24d74a90fa96ce71f8616d9838f25bc5f8b0c41e4223bc0144a2991",
    "UpsertBucket": "a30f4b9373ef4d200d9e927fe21315320dc83fc409c70a7ed64201a2b107bf6d",
    "Viewer": "e5782f8ad76269e0104b45e78e82bc03efcc6783ec68299ac082de12c5475a33"
  },
  "group": "cub200-scratch-100ep-lee-v1",
  "manifestSha256": "b985f79a2d4fa8935ae683ced24d38af1067219cd36b497d59f4d79de78ab7f4",
  "maxFileStreamBodyBytes": 8388608,
  "maxGraphqlBodyBytes": 1048576,
  "noVariableOperations": [
    "ProbeServerCapabilities",
    "Viewer",
    "ServerFeaturesQuery"
  ],
  "project": "alphabet2d-cub200",
  "protocolVersion": "wandb-0.22.3-h200-cub-v1",
  "runFiles": [
    "config.yaml",
    "wandb-summary.json",
    "console.log"
  ],
  "runsById": {
    "11bd3d2693f03946": {
      "displayName": "va_k96-seed509",
      "tags": []
    },
    "178f48621f654868": {
      "displayName": "preflight",
      "tags": []
    },
    "1c6643cabe466261": {
      "displayName": "va_k96-seed501",
      "tags": []
    },
    "2792cfe32fbf0e14": {
      "displayName": "parc_net_s-seed521",
      "tags": []
    },
    "299a711765bbf5ed": {
      "displayName": "convnextv2_atto-seed501",
      "tags": []
    },
    "2f0e25e482e5aeb5": {
      "displayName": "va_k128-seed521",
      "tags": []
    },
    "31969ee743d4da16": {
      "displayName": "connectivity",
      "tags": []
    },
    "46e5fbc01bc80275": {
      "displayName": "convnextv2_atto-seed509",
      "tags": []
    },
    "5471e07f61242b83": {
      "displayName": "tinyvim_s-seed509",
      "tags": []
    },
    "593cefe25457f240": {
      "displayName": "parc_net_s-seed509",
      "tags": []
    },
    "7f7af60be963a0df": {
      "displayName": "va_k128-seed509",
      "tags": []
    },
    "b5da28dd41b55d6f": {
      "displayName": "convnextv2_atto-seed521",
      "tags": []
    },
    "c195c30e276743f1": {
      "displayName": "tinyvim_s-seed501",
      "tags": []
    },
    "de359359eda34881": {
      "displayName": "va_k128-seed501",
      "tags": []
    },
    "e3d696d8337f8772": {
      "displayName": "tinyvim_s-seed521",
      "tags": []
    },
    "f3b6d81193cc6e08": {
      "displayName": "parc_net_s-seed501",
      "tags": []
    },
    "f4e06bc7c0388ae9": {
      "displayName": "va_k96-seed521",
      "tags": []
    }
  },
  "schemaVersion": 1,
  "sdkVersion": "0.22.3",
  "streamFiles": [
    "wandb-history.jsonl",
    "wandb-summary.json"
  ],
  "upsertBucketVariableKeys": [
    "commit",
    "config",
    "debug",
    "description",
    "displayName",
    "entity",
    "groupName",
    "host",
    "id",
    "jobType",
    "name",
    "notes",
    "program",
    "project",
    "repo",
    "state",
    "summaryMetrics",
    "sweep",
    "tags"
  ],
  "upstreamOrigin": "https://api.wandb.ai"
} as const;
