"""Generate the fixed CUB allowlist; no secret material."""
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / 'scripts'))
from cub200_run_ids import run_id

base = ROOT / 'cloudflare/baseline-relay/src'
template = (base / 'dense.generated.ts').read_text()
data = json.loads(template.split('export const CAMPAIGN = ', 1)[1].rsplit(' as const;', 1)[0])
config = json.loads((ROOT / 'h200/cub200/campaign.json').read_text())
names = ['connectivity', 'preflight'] + [f'{m}-seed{s}' for s in config['seeds'] for m in config['models']]
data.update(campaignId=config['campaign_id'], entity=config['wandb_entity'],
    project=config['wandb_project'], group=config['campaign_id'],
    protocolVersion='wandb-0.22.3-h200-cub-v1',
    runsById={run_id(config['campaign_id'], name): {'displayName': name, 'tags': []} for name in names},
    runFiles=['config.yaml', 'wandb-summary.json', 'console.log'])
data.pop('manifestSha256')
data['manifestSha256'] = hashlib.sha256(json.dumps(data, sort_keys=True).encode()).hexdigest()
(base / 'cub.generated.ts').write_text('// Generated by h200/cub200/generate_relay.py\nexport const CAMPAIGN = ' + json.dumps(data, indent=2, sort_keys=True) + ' as const;\n')
