"""Generate a separate dense scope inside the existing secret/IP-scoped relay."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]
GROUP='h200-va-coco-ft501-v2-20260915'
URL='https://lnet-h200-baseline-relay-v1.gpupulse-monitor.workers.dev/dense-v2'


def outputs():
    original=(ROOT/'cloudflare/baseline-relay/src/campaign.generated.ts').read_text()
    contract=json.loads(original.split('export const CAMPAIGN = ',1)[1].rsplit(' as const;',1)[0])
    tags=['H200','COCO','VA-K128','seed501','12ep','optimized-v2','ip-scoped-untrusted']
    runs={}
    for role in ('train','canary'):
        runs[role]={'id':hashlib.sha256(f'{GROUP}:{role}'.encode()).hexdigest()[:16],
                    'display_name':'H200-VA-COCO-ft501-v2' if role=='train' else 'H200-dense-relay-canary-v2',
                    'tags':tags if role=='train' else ['H200','COCO','relay-canary','not-training']}
    runtime={'entity':'daehwa','project':'alphabet2d-dense-transfer','group':GROUP,'wandb_sdk_version':'0.22.3',
             'wandb_base_url':URL,'wandb_app_url':'https://wandb.ai','runs':runs}
    manifest=hashlib.sha256(json.dumps(runtime,sort_keys=True).encode()).hexdigest()
    contract.update(campaignId=GROUP,manifestSha256=manifest,protocolVersion='wandb-0.22.3-h200-dense-v2',
                    project=runtime['project'],group=GROUP,
                    runsById={r['id']:{'displayName':r['display_name'],'tags':r['tags']} for r in runs.values()})
    source=(ROOT/'cloudflare/baseline-relay/src/index.ts').read_text()
    source=source.replace('"./campaign.generated"','"./dense.generated"').replace('h200/run_baselines.sh','h200/run_dense_va_coco_v2.sh')
    # Fixed, non-secret rejection categories make a failed client handshake
    # actionable. No key/IP value, request body or authorization is returned.
    source=source.replace('{ error: "request rejected", request_id: requestId }',
                          '{ error: "request rejected", reason, request_id: requestId }')
    return {
      ROOT/'h200/dense_transfer/wandb-v2.json':json.dumps(runtime,indent=2)+'\n',
      ROOT/'cloudflare/baseline-relay/src/dense.generated.ts':'// Generated by h200/dense_transfer/generate_relay.py\nexport const CAMPAIGN = '+json.dumps(contract,indent=2,sort_keys=True)+' as const;\n',
      ROOT/'cloudflare/baseline-relay/src/dense.ts':source,
    }


def main():
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args()
    for path,value in outputs().items():
        if args.check:
            if not path.exists() or path.read_text()!=value:raise SystemExit('Generated dense contract stale: '+str(path))
        else:path.write_text(value)


if __name__=='__main__':main()
