/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false` (hash: 1aa17cb0bee81d58b99ccbded1fd075e)
interface __BaseEnv_Env {
	RELAY_RATE_LIMITER: RateLimit;
	WANDB_API_KEY: string;
	ALLOWED_EGRESS_IPS: string;
	IN10_OWNER_TOKEN: string;
	IN10_CONTROL: DurableObjectNamespace<import("./src/entry").In10Control>;
	IN10_ARTIFACT: DurableObjectNamespace<import("./src/entry").In10Artifact>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/entry");
		durableNamespaces: "In10Control" | "In10Artifact";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WANDB_API_KEY" | "ALLOWED_EGRESS_IPS" | "IN10_OWNER_TOKEN">> {}
}
